# Generated by Django 6.0.3 on 2026-04-07 22:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_rename_code_language_lang_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.language')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='categories/icons/')),
                ('is_locked', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=500)),
                ('alphabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.alphabet')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(default=0)),
                ('mistakes_count', models.IntegerField(default=0)),
                ('average_keyboard_scale', models.FloatField(default=1.0, help_text='Средний масштаб кнопок за сессию')),
                ('time_spent', models.IntegerField(blank=True, help_text='в секундах', null=True)),
                ('stars_earned', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('average_reaction_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=5)),
                ('audio', models.FileField(blank=True, null=True, upload_to='letters/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='letters/visuals/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to='game.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('current_scale', models.FloatField(default=1.0, help_text='Масштаб интерфейса в момент нажатия')),
                ('reaction_time', models.FloatField(help_text='Время реакции в секундах')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.letter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.gamesession')),
            ],
        ),
    ]
