# Generated by Django 6.0.3 on 2026-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('theme', 'Темы'), ('keyboard', 'Клавиатуры'), ('accessory', 'Аксессуары'), ('sound', 'Звуки')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(help_text="Подзаголовок (например, 'Cool blue ocean vibes')", max_length=255)),
                ('image', models.ImageField(upload_to='shop/icons/')),
                ('price', models.IntegerField(default=50)),
            ],
        ),
    ]
