# Generated by Django 6.0.3 on 2026-04-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='code',
            new_name='lang_code',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='language',
            name='is_active',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='difficulty_factor',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='high_focus_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='larger_touch_targets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='spoken_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='language',
            name='flag_icon',
            field=models.ImageField(null=True, upload_to='languages/'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
