# Generated by Django 6.0.3 on 2026-04-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_code_language_lang_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='exp',
            field=models.PositiveIntegerField(default=0, help_text='Опыт ребенка'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='last_reward_date',
            field=models.DateField(blank=True, help_text='Дата последнего бонуса', null=True),
        ),
    ]
