# Generated by Django 6.0.3 on 2026-04-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_childprofile_exp_childprofile_last_reward_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='preferred_initial_scale',
            field=models.FloatField(default=1.0),
        ),
    ]
