# Generated by Django 6.0.3 on 2026-05-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_shopitem'),
        ('user', '0004_childprofile_preferred_initial_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='active_keyboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_keyboards', to='game.shopitem'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='active_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_themes', to='game.shopitem'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, related_name='owners', to='game.shopitem'),
        ),
    ]
